source 'https://github.com/CocoaPods/Specs.git'
platform:ios,'8.0'
## 忽略引入库的所有警告（强迫症者的福音啊）
#inhibit_all_warnings!
#use_frameworks!
target "CGXCategoryKit-OC" do
  
  pod 'CGXCategoryKitOC', :path => '../'

end

